### ISSUE TITLE
404 error when the agent hits the APM-Server

### ISSUE THREAD

**Issue by ghost** [philkra/elastic-apm-laravel#20]
Hey, I'm not very knowlesabe with Laravel or the APM-server. I was wondering if you can help me with this issue I'm having :).
When the PHP-Agent sends a porst request to the APM-Server's URL it results in a 404 error.

I'm not sure why this is as I have a Java-Agent hitting the same port and the data is showing up in Elasticsearch.

This is the error log that appears when testing.

```
[2018-11-15 09:30:49] local.ERROR: Client error: `POST https://1.1.1.1:8200/6.4.2/transactions` resulted in a `404 Not Found` response:
404 page not found
 {"userId":1545,"email":"test@test.com","exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 404): Client error: `POST https://1.1.1.1:8200/6.4.2/transactions` resulted in a `404 Not Found` response:
404 page not found
 at /home/vagrant/code/tmp/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]
#0 /home/vagrant/code/tmp/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))
#1 /home/vagrant/code/tmp/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))
#2 /home/vagrant/code/tmp/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), Array)
#3 /home/vagrant/code/tmp/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#4 /home/vagrant/code/tmp/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\TaskQueue->run(true)
#5 /home/vagrant/code/tmp/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#6 /home/vagrant/code/tmp/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()
#7 /home/vagrant/code/tmp/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#8 /home/vagrant/code/tmp/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#9 /home/vagrant/code/tmp/vendor/guzzlehttp/guzzle/src/Client.php(106): GuzzleHttp\\Promise\\Promise->wait()
#10 /home/vagrant/code/tmp/vendor/philkra/elastic-apm-php-agent/src/Middleware/Connector.php(59): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Psr7\\Request))
#11 /home/vagrant/code/tmp/vendor/philkra/elastic-apm-php-agent/src/Agent.php(230): PhilKra\\Middleware\\Connector->sendTransactions(Object(PhilKra\\Stores\\TransactionsStore))
#12 /home/vagrant/code/tmp/vendor/philkra/elastic-apm-laravel/src/Middleware/RecordTransaction.php(73): PhilKra\\Agent->send()
#13 /home/vagrant/code/tmp/app/Http/Middleware/RecordTransaction.php(20): PhilKra\\ElasticApmLaravel\\Middleware\\RecordTransaction->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#14 /home/vagrant/code/tmp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(218): App\\Http\\Middleware\\RecordTransaction->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#15 /home/vagrant/code/tmp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#16 /home/vagrant/code/tmp/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#17 {main}
"} 
```

**Comment by philkra** [comment]
hi, can please attach the config of the agent? I guess, I have a hunch what the problem could be..

**Comment by ghost** [comment]
```
<?php

return [
    // Sets whether the apm reporting should be active or not
    'active' => env('APM_ACTIVE', false),

    'app' => [
        // The app name that will identify your app in Kibana / Elastic APM
        'appName' => env('APP_ENV', 'local').'-apm',

        // The version of your app
        'appVersion' => '',
    ],

    'env' => [
        // whitelist environment variables OR send everything
        'env' => ['DOCUMENT_ROOT', 'REMOTE_ADDR']
        //'env' => []
    ],

    'server' => [
        // The apm-server to connect to
        'serverUrl' => 'https://1.1.1.1:8200',

        // Token for x
        // 'secretToken' => '',

        // API version of the apm agent you connect to
        'apmVersion' => '6.4.2',

        // Hostname of the system the agent is running on.
        'hostname' => 'stage-php',

        'active' => env('APM_ACTIVE', false),
    ],

    'spans' => [
        // Depth of backtraces
        'backtraceDepth'=> 25,

        // Add source code to span
        'renderSource' => true,

        'querylog' => [
            // Set to false to completely disable query logging, or to 'auto' if you would like to use the threshold feature.
            'enabled' => true,

            // If a query takes longer then 200ms, we enable the query log. Make sure you set enabled = 'auto'
            'threshold' => 200,
        ],
    ],
];
```

**Comment by philkra** [comment]
My hunch was correct, the error is that you are overwriting the `apmVersion` to a non existing endpoint. You need to change the config of `'apmVersion' => '6.4.2',` to `'apmVersion' => 'v1',` or simply remove that key from your config as it has a default value. 

Does it work now?

**Comment by ghost** [comment]
ah nice, that works wonderfully now. 
Sorry I thought it's like in the other Elastic Agents that you'd have to put the APM-Server's versions.

Thanks for your help and the this Agent :)

**Comment by philkra** [comment]
you are welcome!
