### ISSUE TITLE
BindingResolutionException when using Lumen.

### ISSUE THREAD

**Issue by immomo808** [philkra/elastic-apm-laravel#55]
Hi,

I got this error when I tried to use this in Lumen.
Does anyone know how to solve it? (Or it doesn't support lumen?)

Here is the error in logs.

```
[2019-07-31 09:18:35] local.ERROR: Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class PhilKra\Agent in /Users/user/blog/vendor/illuminate/container/Container.php:977
Stack trace:
#0 /Users/user/blog/vendor/illuminate/container/Container.php(915): Illuminate\Container\Container->unresolvablePrimitive(Object(ReflectionParameter))
#1 /Users/user/blog/vendor/illuminate/container/Container.php(856): Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#2 /Users/user/blog/vendor/illuminate/container/Container.php(818): Illuminate\Container\Container->resolveDependencies(Array)
#3 /Users/user/blog/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('PhilKra\\Agent')
#4 /Users/user/blog/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('PhilKra\\Agent', Array)
#5 /Users/user/blog/vendor/laravel/lumen-framework/src/Application.php(267): Illuminate\Container\Container->make('PhilKra\\Agent', Array)
#6 /Users/user/blog/vendor/illuminate/container/Container.php(929): Laravel\Lumen\Application->make('PhilKra\\Agent')
#7 /Users/user/blog/vendor/illuminate/container/Container.php(857): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#8 /Users/user/blog/vendor/illuminate/container/Container.php(818): Illuminate\Container\Container->resolveDependencies(Array)
#9 /Users/user/blog/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('PhilKra\\Elastic...')
#10 /Users/user/blog/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('PhilKra\\Elastic...', Array)
#11 /Users/user/blog/vendor/laravel/lumen-framework/src/Application.php(267): Illuminate\Container\Container->make('PhilKra\\Elastic...', Array)
#12 /Users/user/blog/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(140): Laravel\Lumen\Application->make('PhilKra\\Elastic...')
#13 /Users/user/blog/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(117): Laravel\Lumen\Application->callTerminableMiddleware(Object(Illuminate\Http\Response))
#14 /Users/user/blog/public/index.php(28): Laravel\Lumen\Application->run()
#15 {main} {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class PhilKra\\Agent at /Users/user/blog/vendor/illuminate/container/Container.php:977)
[stacktrace]
#0 /Users/user/blog/vendor/illuminate/container/Container.php(915): Illuminate\\Container\\Container->unresolvablePrimitive(Object(ReflectionParameter))
#1 /Users/user/blog/vendor/illuminate/container/Container.php(856): Illuminate\\Container\\Container->resolvePrimitive(Object(ReflectionParameter))
#2 /Users/user/blog/vendor/illuminate/container/Container.php(818): Illuminate\\Container\\Container->resolveDependencies(Array)
#3 /Users/user/blog/vendor/illuminate/container/Container.php(667): Illuminate\\Container\\Container->build('PhilKra\\\\Agent')
#4 /Users/user/blog/vendor/illuminate/container/Container.php(615): Illuminate\\Container\\Container->resolve('PhilKra\\\\Agent', Array)
#5 /Users/user/blog/vendor/laravel/lumen-framework/src/Application.php(267): Illuminate\\Container\\Container->make('PhilKra\\\\Agent', Array)
#6 /Users/user/blog/vendor/illuminate/container/Container.php(929): Laravel\\Lumen\\Application->make('PhilKra\\\\Agent')
#7 /Users/user/blog/vendor/illuminate/container/Container.php(857): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#8 /Users/user/blog/vendor/illuminate/container/Container.php(818): Illuminate\\Container\\Container->resolveDependencies(Array)
#9 /Users/user/blog/vendor/illuminate/container/Container.php(667): Illuminate\\Container\\Container->build('PhilKra\\\\Elastic...')
#10 /Users/user/blog/vendor/illuminate/container/Container.php(615): Illuminate\\Container\\Container->resolve('PhilKra\\\\Elastic...', Array)
#11 /Users/user/blog/vendor/laravel/lumen-framework/src/Application.php(267): Illuminate\\Container\\Container->make('PhilKra\\\\Elastic...', Array)
#12 /Users/user/blog/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(140): Laravel\\Lumen\\Application->make('PhilKra\\\\Elastic...')
#13 /Users/user/blog/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(117): Laravel\\Lumen\\Application->callTerminableMiddleware(Object(Illuminate\\Http\\Response))
#14 /Users/user/blog/public/index.php(28): Laravel\\Lumen\\Application->run()
#15 {main}
"}
```

**Comment by immomo808** [comment]
I found the solution here. 
https://github.com/philkra/elastic-apm-laravel/pull/57
I will close this issue.
