### ISSUE TITLE
TypeError: Return value of PhilKra\Events\EventBean::getEnv() must be an instance of PhilKra\Events\object,

### ISSUE THREAD

**Issue by marafee1243** [philkra/elastic-apm-laravel#75]
I installed and configure two packages in laravel app.

"laravel/framework": "5.5.*",
"philkra/elastic-apm-laravel": "5.8.0",
 "philkra/elastic-apm-php-agent": "6.5.3",
 "ralouphie/getallheaders": "2.0.5",
 
 PHP 7.1.32
 
 I followed the documentation and configured. Set the environment in `.env`
 
 ```
 # APM Configs
APM_ACTIVE=true
APM_APPNAME=myapp
APM_SERVERURL=http://elk.local
APM_SECRETTOKEN=none

 ```

I get these errors in laravel logs.

```
[2021-08-13 12:57:09] local.ERROR: TypeError: Return value of PhilKra\Events\EventBean::getEnv() must be an instance of PhilKra\Events\object, instance of stdClass returned in /Applications/MAMP/htdocs/projects/Villars_V32_CMS/vendor/philkra/elastic-apm-php-agent/src/Events/EventBean.php:183
Stack trace:
#0 /Applications/MAMP/htdocs/projects/Villars_V32_CMS/vendor/philkra/elastic-apm-php-agent/src/Events/EventBean.php(253): PhilKra\Events\EventBean->getEnv()
#1 /Applications/MAMP/htdocs/projects/Villars_V32_CMS/vendor/philkra/elastic-apm-php-agent/src/Events/Transaction.php(157): PhilKra\Events\EventBean->getContext()
#2 [internal function]: PhilKra\Events\Transaction->jsonSerialize()
#3 /Applications/MAMP/htdocs/projects/Villars_V32_CMS/vendor/philkra/elastic-apm-php-agent/src/Middleware/Connector.php(71): json_encode(Object(PhilKra\Serializers\Transactions))
#4 /Applications/MAMP/htdocs/projects/Villars_V32_CMS/vendor/philkra/elastic-apm-php-agent/src/Agent.php(239): PhilKra\Middleware\Connector->sendTransactions(Object(PhilKra\Stores\TransactionsStore))
#5 /Applications/MAMP/htdocs/projects/Villars_V32_CMS/vendor/philkra/elastic-apm-laravel/src/Middleware/RecordTransaction.php(85): PhilKra\Agent->send()
#6 /Applications/MAMP/htdocs/projects/Villars_V32_CMS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(218): PhilKra\ElasticApmLaravel\Middleware\RecordTransaction->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\JsonResponse))
#7 /Applications/MAMP/htdocs/projects/Villars_V32_CMS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\JsonResponse))
#8 /Applications/MAMP/htdocs/projects/Villars_V32_CMS/public/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\JsonResponse))
```

**Comment by dstepe** [comment]
First, this package is no longer supported and you should really look at an alternative such as [arkaitzgarro/elastic-apm-laravel](https://github.com/arkaitzgarro/elastic-apm-laravel).

In this particular case, the version of the APM Agent package you are using contains a return type hint of `object` for the referenced method. Support for the `object` type hint was not added until PHP 7.2. It does appear that later versions of the package address that by using an array for the returned value.

If you can't update the versions of PHP and the packages you are using (none of which appear to be supported any longer), you can probably use a different release of `philkra/elastic-apm-php-agent` and it will work. For example, [6.5.8](https://github.com/philkra/elastic-apm-php-agent/blob/6.5.8/src/Events/EventBean.php#L230) uses the `array` return type.

**Comment by philkra** [comment]
closing as repo is going to be achived.
